name: kop build test images test

on:
  pull_request:
    branches: 
      - master
    paths:
      - 'integrations/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build test images
      run: |
        ./integrations/build.sh
