name: kop mvn build check and unit tests

on:
  pull_request:
    branches:
      - master
      - branch-*
  push:
    branches:
      - master
      - branch-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: License check
      run: mvn -ntp -B license:check

    - name: Build with Maven skipTests
      run: mvn clean install -ntp -B -DskipTests

    - name: Style check
      run: mvn -ntp -B checkstyle:check

    - name: Spotbugs check
      run: mvn -ntp -B spotbugs:check

    - name: kafka-impl test after build
      run: mvn test -ntp -B -DfailIfNoTests=false -pl kafka-impl

    - name: kafka-payload-processor test after build
      run: mvn test -ntp -B -DfailIfNoTests=false -pl kafka-payload-processor-shaded-tests

    - name: package surefire artifacts
      if: failure()
      run: |
        rm -rf artifacts
        mkdir artifacts
        find . -type d -name "*surefire*" -exec cp --parents -R {} artifacts/ \;
        zip -r artifacts.zip artifacts

    - uses: actions/upload-artifact@master
      name: upload surefire-artifacts
      if: failure()
      with:
        name: surefire-artifacts
        path: artifacts.zip
