name: kop pr validation

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'src/**'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: License check
      run: mvn license:check

    - name: Style check
      run: mvn checkstyle:check

    - name: Spotbugs check
      run: mvn spotbugs:check
