name: KoP Release Notes

on:
  push:
    branches:
    - master
    path-ignores:
    - docs/**
    - README.md
    - CONTRIBUTING.md
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to cloudsmith
      run: docker login -u="${{ secrets.CLOUDSMITH_USERNAME }}" -p="${{ secrets.CLOUDSMITH_API_KEY
        }}" docker.cloudsmith.io
      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - name: release note
      uses: toolmantim/release-drafter@v5.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
